import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { getConfigDir, getConfigFilePath, getMcpDir, getToken, hasToken, removeToken, saveToken, setMcpDir } from "./config.js";
import { extractFigmaProject } from "./extractor.js";
import { loadProjectsRegistry, startHttpMcpServer, startMcpServer } from "./server.js";

function getLocalNetworkIp() {
  const nets = os.networkInterfaces();
  for (const name of Object.keys(nets)) {
    for (const net of nets[name] || []) {
      if (net.family === "IPv4" && !net.internal) {
        return net.address;
      }
    }
  }
  return "localhost";
}

function printHelp() {
  console.log(`
dims - Figma Extractor & Local/Remote MCP Server Hub

USAGE:
  dims <command> [arguments] [options] (or: dims-extract)

COMMANDS:
  auth [token]              Store and encrypt your Figma Personal Access Token
  auth --status             Check current authentication status
  auth --logout             Remove stored Figma token
  add <url> [name]          Download and extract a Figma project into local MCP hub
  list, ls                  List all extracted Figma projects
  remove, rm <name>         Delete an extracted project from local MCP hub
  serve                     Start the MCP server (stdio mode for local AI client)
  serve --remote            Start the MCP server as a Remote HTTP/SSE server (for 2nd laptop)
  setup-cli                 Install 'dims' directly to user PATH without sudo
  mcp-config                Show ready-to-use configuration for OpenCode, Claude Desktop, Cursor
  config                    Show current storage paths and settings
  help, --help, -h          Show this help message

OPTIONS FOR SERVE:
  --remote                  Run in Remote Network HTTP/SSE mode
  --port, -p <number>       Specify port for remote server (default: 3456)
  --host <ip>               Specify host to bind (default: 0.0.0.0)

EXAMPLES:
  dims auth figd_your_token_here
  dims add "https://www.figma.com/design/AbCdEf123456/SampleDesign" my-app
  dims list
  dims serve                  # Local Stdio MCP mode
  dims serve --remote         # Remote SSE mode for Laptop 2
`);
}

function ensureMcpStandaloneRunner(mcpDir) {
  const standaloneServerPath = path.join(mcpDir, "server.js");
  const pkgPath = path.join(mcpDir, "package.json");

  if (!fs.existsSync(pkgPath)) {
    fs.writeFileSync(
      pkgPath,
      JSON.stringify(
        {
          name: "dims-extract-mcp",
          version: "1.1.0",
          type: "module",
          description: "Local MCP Server generated by dims-extract",
          main: "server.js",
        },
        null,
        2
      ),
      "utf8"
    );
  }

  const runnerScript = `#!/usr/bin/env node
import { startMcpServer } from "dims-extract";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
startMcpServer(__dirname);
`;
  if (!fs.existsSync(standaloneServerPath)) {
    try {
      fs.writeFileSync(standaloneServerPath, runnerScript, "utf8");
      fs.chmodSync(standaloneServerPath, 0o755);
    } catch {
      // Ignore write errors if permissions restricted
    }
  }
}

export async function runCli(argv = process.argv.slice(2)) {
  const command = argv[0] || "help";
  const mcpDir = getMcpDir();
  ensureMcpStandaloneRunner(mcpDir);

  switch (command.toLowerCase()) {
    case "auth": {
      const subArg = argv[1];
      if (subArg === "--logout" || subArg === "logout") {
        removeToken();
        console.log("[dims-extract] Stored Figma token has been removed.");
        return;
      }
      if (subArg === "--status" || subArg === "status" || !subArg) {
        if (hasToken()) {
          console.log(`[dims-extract] Authenticated. Encrypted token is active in: ${getConfigFilePath()}`);
        } else {
          console.log("[dims-extract] Not authenticated. Run 'dims-extract auth <token>' to store your Figma Personal Access Token.");
        }
        return;
      }

      saveToken(subArg);
      console.log(`[dims-extract] Token encrypted and stored successfully in OS config: ${getConfigFilePath()}`);
      return;
    }

    case "add":
    case "extract": {
      const urlOrKey = argv[1];
      const projectSlug = argv[2];

      if (!urlOrKey) {
        console.error("Error: Please provide a Figma design URL or File Key.");
        console.error("Usage: dims-extract add <figma-url> [project-name]");
        process.exit(1);
      }

      const token = getToken();
      if (!token) {
        console.error("Error: No Figma token found.");
        console.error("Please run 'dims-extract auth <token>' first or set the FIGMA_TOKEN environment variable.");
        process.exit(1);
      }

      try {
        console.log(`[dims-extract] Starting extraction into: ${mcpDir}`);
        const result = await extractFigmaProject({
          fileKeyOrUrl: urlOrKey,
          token,
          projectSlug,
          mcpRootDir: mcpDir,
          onProgress: (msg) => console.log(msg),
        });

        console.log(`\n🎉 Project "${result.name}" (${result.project}) extracted successfully!`);
        console.log(`  - Screens: ${result.screenCount}`);
        console.log(`  - Components: ${result.componentCount}`);
        console.log(`  - Rendered Images (2x): ${result.imageCount}`);
        console.log(`  - Path: ${result.outputDir}`);
        console.log("\nThis project is now immediately available in your MCP server.");
      } catch (err) {
        console.error(`\n[dims-extract] Extraction failed: ${err.message}`);
        process.exit(1);
      }
      return;
    }

    case "list":
    case "ls": {
      const registry = loadProjectsRegistry(mcpDir);
      const projects = Object.values(registry);

      console.log(`[dims-extract] MCP Hub Directory: ${mcpDir}`);
      if (projects.length === 0) {
        console.log("\nNo projects extracted yet.");
        console.log("Run 'dims-extract add <figma-url>' to extract your first project.");
        return;
      }

      console.log(`\nFound ${projects.length} project(s):\n`);
      for (const p of projects) {
        const meta = p.metadata || {};
        console.log(`  • ${p.slug.padEnd(20)} | "${meta.name || p.slug}"`);
        console.log(`    Screens: ${p.screens.length} | Components: ${p.components.length} | Last Modified: ${meta.lastModified || "N/A"}`);
        console.log(`    Location: ${p.dir}\n`);
      }
      return;
    }

    case "remove":
    case "rm":
    case "delete": {
      const targetSlug = argv[1];
      if (!targetSlug) {
        console.error("Error: Please specify the project name to remove.");
        console.error("Usage: dims-extract remove <project-name>");
        process.exit(1);
      }

      const targetPath = path.join(mcpDir, "projects", targetSlug);
      if (!fs.existsSync(targetPath)) {
        console.error(`Error: Project "${targetSlug}" does not exist at ${targetPath}`);
        process.exit(1);
      }

      fs.rmSync(targetPath, { recursive: true, force: true });
      console.log(`[dims-extract] Project "${targetSlug}" has been successfully removed.`);
      return;
    }

    case "serve": {
      const isRemote = argv.includes("--remote");
      const portIdx = argv.findIndex((a) => a === "--port" || a === "-p");
      const customPort = portIdx !== -1 && argv[portIdx + 1] ? Number.parseInt(argv[portIdx + 1], 10) : null;
      const hostIdx = argv.findIndex((a) => a === "--host");
      const customHost = hostIdx !== -1 && argv[hostIdx + 1] ? argv[hostIdx + 1] : "0.0.0.0";

      if (isRemote || customPort !== null) {
        const port = customPort || 3456;
        const lanIp = getLocalNetworkIp();

        startHttpMcpServer({
          port,
          host: customHost,
          mcpRootDir: mcpDir,
        });

        console.log(`
============================================================
dims-extract Remote MCP Server is RUNNING (HTTP/SSE)
============================================================
• Local URL       : http://localhost:${port}/sse
• Network URL     : http://${lanIp}:${port}/sse
• Health / Info   : http://${lanIp}:${port}/health
• Static Images   : http://${lanIp}:${port}/images/<project>/...

------------------------------------------------------------
Configuration for Laptop 2 (OpenCode 'opencode.json'):
------------------------------------------------------------
{
  "$schema": "https://opencode.ai/config.json",
  "mcp": {
    "dims-figma": {
      "type": "sse",
      "url": "http://${lanIp}:${port}/sse"
    }
  }
}

------------------------------------------------------------
Configuration for Laptop 2 (Claude Desktop):
------------------------------------------------------------
{
  "mcpServers": {
    "dims-figma": {
      "url": "http://${lanIp}:${port}/sse"
    }
  }
}
============================================================
Listening for connections from Laptop 2... (Press Ctrl+C to stop)
`);
        return;
      }

      // Default: Stdio mode
      startMcpServer(mcpDir);
      return;
    }

    case "mcp-config": {
      const lanIp = getLocalNetworkIp();
      console.log(`
============================================================
Ready-to-use MCP Configurations for dims
MCP Hub Directory: ${mcpDir}
============================================================

A. MODE 1: LOCAL (Used on Laptop 1 where dims is installed)
------------------------------------------------------------
1. OpenCode (add to "opencode.json"):
{
  "$schema": "https://opencode.ai/config.json",
  "mcp": {
    "dims-figma": {
      "type": "stdio",
      "command": "dims",
      "args": ["serve"]
    }
  }
}

2. Claude Desktop ("claude_desktop_config.json"):
{
  "mcpServers": {
    "dims-figma": {
      "command": "dims",
      "args": ["serve"]
    }
  }
}


B. MODE 2: REMOTE (Used on Laptop 2 via WiFi / LAN)
Step 1: On Laptop 1, run:
  dims serve --remote

Step 2: On Laptop 2, configure OpenCode ("opencode.json"):
{
  "$schema": "https://opencode.ai/config.json",
  "mcp": {
    "dims-figma": {
      "type": "sse",
      "url": "http://${lanIp}:3456/sse"
    }
  }
}
`);
      return;
    }

    case "setup-cli": {
      const isWin = process.platform === "win32";
      const binDir = path.join(os.homedir(), ".local", "bin");
      fs.mkdirSync(binDir, { recursive: true });

      if (isWin) {
        const cmdDims = path.join(binDir, "dims.cmd");
        const cmdExtract = path.join(binDir, "dims-extract.cmd");
        fs.writeFileSync(cmdDims, "@echo off\r\nnpx -y dims-extract %*\r\n", "utf8");
        fs.writeFileSync(cmdExtract, "@echo off\r\nnpx -y dims-extract %*\r\n", "utf8");
        console.log(`[dims] Launchers created at: ${cmdDims} and ${cmdExtract}`);
      } else {
        const scriptDims = path.join(binDir, "dims");
        const scriptExtract = path.join(binDir, "dims-extract");
        const launcherBody = "#!/usr/bin/env bash\nexec npx -y dims-extract \"$@\"\n";
        fs.writeFileSync(scriptDims, launcherBody, "utf8");
        fs.chmodSync(scriptDims, 0o755);
        fs.writeFileSync(scriptExtract, launcherBody, "utf8");
        fs.chmodSync(scriptExtract, 0o755);
        console.log(`[dims] Launchers created at: ${scriptDims} and ${scriptExtract}`);

        const shell = process.env.SHELL || "";
        const rcFile = shell.includes("zsh") ? path.join(os.homedir(), ".zshrc") : path.join(os.homedir(), ".bashrc");
        const currentPath = process.env.PATH || "";
        if (!currentPath.includes(binDir) && fs.existsSync(rcFile)) {
          const content = fs.readFileSync(rcFile, "utf8");
          if (!content.includes(".local/bin")) {
            fs.appendFileSync(rcFile, `\nexport PATH="$HOME/.local/bin:$PATH"\n`);
            console.log(`[dims] Added ~/.local/bin to PATH in ${rcFile}`);
          }
        }
      }

      console.log("\n🎉 CLI setup completed! You can now run:");
      console.log("  dims --help\n");
      return;
    }

    case "config": {
      console.log(`
[dims-extract Configuration]
  • OS Config Directory : ${getConfigDir()}
  • Config File Path    : ${getConfigFilePath()}
  • MCP Hub Directory   : ${mcpDir}
  • Figma Token Status  : ${hasToken() ? "Authenticated (Encrypted)" : "Not configured"}
  • Primary Network IP  : ${getLocalNetworkIp()}
`);
      return;
    }

    case "help":
    case "--help":
    case "-h":
    default:
      printHelp();
      return;
  }
}
