import fs from "node:fs";
import path from "node:path";
import { getConfigDir, getConfigFilePath, getMcpDir, getToken, hasToken, removeToken, saveToken, setMcpDir } from "./config.js";
import { extractFigmaProject } from "./extractor.js";
import { loadProjectsRegistry, startMcpServer } from "./server.js";

function printHelp() {
  console.log(`
dims-extract - Figma Extractor & Local MCP Server Hub

USAGE:
  dims-extract <command> [arguments] [options]

COMMANDS:
  auth [token]              Store and encrypt your Figma Personal Access Token
  auth --status             Check current authentication status
  auth --logout             Remove stored Figma token
  add <url> [name]          Download and extract a Figma project into local MCP hub
  list, ls                  List all extracted Figma projects
  remove, rm <name>         Delete an extracted project from local MCP hub
  serve                     Start the local MCP server over stdio
  mcp-config                Show ready-to-use configuration for OpenCode, Claude Desktop, Cursor
  config                    Show current storage paths and settings
  help, --help, -h          Show this help message

EXAMPLES:
  dims-extract auth figd_abc123xyz
  dims-extract add "https://www.figma.com/design/YCbLdntydnVO7uFv7wfpJg/Archiva" archiva
  dims-extract list
  dims-extract serve
  dims-extract mcp-config
`);
}

// Generate a standalone runner in dims-extract-mcp folder so it can run independently
function ensureMcpStandaloneRunner(mcpDir) {
  const standaloneServerPath = path.join(mcpDir, "server.js");
  const pkgPath = path.join(mcpDir, "package.json");

  if (!fs.existsSync(pkgPath)) {
    fs.writeFileSync(
      pkgPath,
      JSON.stringify(
        {
          name: "dims-extract-mcp",
          version: "1.0.0",
          type: "module",
          description: "Local MCP Server generated by dims-extract",
          main: "server.js",
        },
        null,
        2
      ),
      "utf8"
    );
  }

  // Copy or write server runner
  const runnerScript = `#!/usr/bin/env node
import { startMcpServer } from "dims-extract";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
startMcpServer(__dirname);
`;
  if (!fs.existsSync(standaloneServerPath)) {
    try {
      fs.writeFileSync(standaloneServerPath, runnerScript, "utf8");
      fs.chmodSync(standaloneServerPath, 0o755);
    } catch {
      // Ignore write errors if permissions restricted
    }
  }
}

export async function runCli(argv = process.argv.slice(2)) {
  const command = argv[0] || "help";
  const mcpDir = getMcpDir();
  ensureMcpStandaloneRunner(mcpDir);

  switch (command.toLowerCase()) {
    case "auth": {
      const subArg = argv[1];
      if (subArg === "--logout" || subArg === "logout") {
        removeToken();
        console.log("[dims-extract] Stored Figma token has been removed.");
        return;
      }
      if (subArg === "--status" || subArg === "status" || !subArg) {
        if (hasToken()) {
          console.log(`[dims-extract] Authenticated. Encrypted token is active in: ${getConfigFilePath()}`);
        } else {
          console.log("[dims-extract] Not authenticated. Run 'dims-extract auth <token>' to store your Figma Personal Access Token.");
        }
        return;
      }

      saveToken(subArg);
      console.log(`[dims-extract] Token encrypted and stored successfully in OS config: ${getConfigFilePath()}`);
      return;
    }

    case "add":
    case "extract": {
      const urlOrKey = argv[1];
      const projectSlug = argv[2];

      if (!urlOrKey) {
        console.error("Error: Please provide a Figma design URL or File Key.");
        console.error("Usage: dims-extract add <figma-url> [project-name]");
        process.exit(1);
      }

      const token = getToken();
      if (!token) {
        console.error("Error: No Figma token found.");
        console.error("Please run 'dims-extract auth <token>' first or set the FIGMA_TOKEN environment variable.");
        process.exit(1);
      }

      try {
        console.log(`[dims-extract] Starting extraction into: ${mcpDir}`);
        const result = await extractFigmaProject({
          fileKeyOrUrl: urlOrKey,
          token,
          projectSlug,
          mcpRootDir: mcpDir,
          onProgress: (msg) => console.log(msg),
        });

        console.log(`\n🎉 Project "${result.name}" (${result.project}) extracted successfully!`);
        console.log(`  - Screens: ${result.screenCount}`);
        console.log(`  - Components: ${result.componentCount}`);
        console.log(`  - Rendered Images (2x): ${result.imageCount}`);
        console.log(`  - Path: ${result.outputDir}`);
        console.log("\nThis project is now immediately available in your MCP server.");
      } catch (err) {
        console.error(`\n[dims-extract] Extraction failed: ${err.message}`);
        process.exit(1);
      }
      return;
    }

    case "list":
    case "ls": {
      const registry = loadProjectsRegistry(mcpDir);
      const projects = Object.values(registry);

      console.log(`[dims-extract] MCP Hub Directory: ${mcpDir}`);
      if (projects.length === 0) {
        console.log("\nNo projects extracted yet.");
        console.log("Run 'dims-extract add <figma-url>' to extract your first project.");
        return;
      }

      console.log(`\nFound ${projects.length} project(s):\n`);
      for (const p of projects) {
        const meta = p.metadata || {};
        console.log(`  • ${p.slug.padEnd(20)} | "${meta.name || p.slug}"`);
        console.log(`    Screens: ${p.screens.length} | Components: ${p.components.length} | Last Modified: ${meta.lastModified || "N/A"}`);
        console.log(`    Location: ${p.dir}\n`);
      }
      return;
    }

    case "remove":
    case "rm":
    case "delete": {
      const targetSlug = argv[1];
      if (!targetSlug) {
        console.error("Error: Please specify the project name to remove.");
        console.error("Usage: dims-extract remove <project-name>");
        process.exit(1);
      }

      const targetPath = path.join(mcpDir, "projects", targetSlug);
      if (!fs.existsSync(targetPath)) {
        console.error(`Error: Project "${targetSlug}" does not exist at ${targetPath}`);
        process.exit(1);
      }

      fs.rmSync(targetPath, { recursive: true, force: true });
      console.log(`[dims-extract] Project "${targetSlug}" has been successfully removed.`);
      return;
    }

    case "serve": {
      startMcpServer(mcpDir);
      return;
    }

    case "mcp-config": {
      console.log(`
============================================================
Ready-to-use MCP Configurations for dims-extract
MCP Hub Directory: ${mcpDir}
============================================================

1. OpenCode (add to "opencode.json"):
------------------------------------------------------------
{
  "$schema": "https://opencode.ai/config.json",
  "mcp": {
    "dims-figma": {
      "type": "stdio",
      "command": "npx",
      "args": ["-y", "dims-extract", "serve"]
    }
  }
}

2. Claude Desktop ("claude_desktop_config.json"):
------------------------------------------------------------
{
  "mcpServers": {
    "dims-figma": {
      "command": "npx",
      "args": ["-y", "dims-extract", "serve"]
    }
  }
}

3. Alternative (Direct Node path without npx):
------------------------------------------------------------
{
  "mcp": {
    "dims-figma": {
      "type": "stdio",
      "command": "node",
      "args": ["${path.join(mcpDir, "server.js").replace(/\\/g, "/")}"]
    }
  }
}
`);
      return;
    }

    case "config": {
      console.log(`
[dims-extract Configuration]
  • OS Config Directory : ${getConfigDir()}
  • Config File Path    : ${getConfigFilePath()}
  • MCP Hub Directory   : ${mcpDir}
  • Figma Token Status  : ${hasToken() ? "Authenticated (Encrypted)" : "Not configured"}
`);
      return;
    }

    case "help":
    case "--help":
    case "-h":
    default:
      printHelp();
      return;
  }
}
